# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilde',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=siteapp.models.upload_locationB, width_field='width_field'),
        ),
    ]
