# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import siteapp.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_auto_20170926_09412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Htmlsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('html', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='bilde',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=siteapp.models.upload_locationB, width_field='width_field'),
        ),
    ]
