# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 10:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0006_auto_20170929_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilde',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=siteapp.models.upload_locationB, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='htmlsite',
            name='html',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
