# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 10:52
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0007_auto_20170929_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilde',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=siteapp.models.upload_locationB, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='htmlsite',
            name='html',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10000),
        ),
    ]
